FROM premhashmap/cain-buildenv:latest
RUN mkdir -p $GOPATH/src/github.com/prem0132 && cd $GOPATH/src/github.com/prem0132 \
    && git clone https://github.com/prem0132/cain.git && cd cain \
    && git checkout cain-incremental-backup \
    && make build
COPY cain /usr/local/bin/cain
RUN addgroup -g 1001 -S cain \
    && adduser -u 1001 -D -S -G cain cain
USER cain
WORKDIR /home/cain
CMD ["cain"]
